package com.boundinteractive.kmmsample

object DummyResponses {
    const val repositories = "[{" +
            "    \"id\": 9993977," +
            "    \"node_id\": \"MDEwOlJlcG9zaXRvcnk5OTkzOTc3\"," +
            "    \"name\": \"MelbourneCocoaHeadsHistory\"," +
            "    \"full_name\": \"melbournecocoa/MelbourneCocoaHeadsHistory\"," +
            "    \"private\": false," +
            "    \"owner\": {" +
            "      \"login\": \"melbournecocoa\"," +
            "      \"id\": 8436888," +
            "      \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjg0MzY4ODg=\"," +
            "      \"avatar_url\": \"https://avatars.githubusercontent.com/u/8436888?v=4\"," +
            "      \"gravatar_id\": \"\"," +
            "      \"url\": \"https://api.github.com/users/melbournecocoa\"," +
            "      \"html_url\": \"https://github.com/melbournecocoa\"," +
            "      \"followers_url\": \"https://api.github.com/users/melbournecocoa/followers\"," +
            "      \"following_url\": \"https://api.github.com/users/melbournecocoa/following{/other_user}\"," +
            "      \"gists_url\": \"https://api.github.com/users/melbournecocoa/gists{/gist_id}\"," +
            "      \"starred_url\": \"https://api.github.com/users/melbournecocoa/starred{/owner}{/repo}\"," +
            "      \"subscriptions_url\": \"https://api.github.com/users/melbournecocoa/subscriptions\"," +
            "      \"organizations_url\": \"https://api.github.com/users/melbournecocoa/orgs\"," +
            "      \"repos_url\": \"https://api.github.com/users/melbournecocoa/repos\"," +
            "      \"events_url\": \"https://api.github.com/users/melbournecocoa/events{/privacy}\"," +
            "      \"received_events_url\": \"https://api.github.com/users/melbournecocoa/received_events\"," +
            "      \"type\": \"Organization\"," +
            "      \"site_admin\": false" +
            "    }," +
            "    \"html_url\": \"https://github.com/melbournecocoa/MelbourneCocoaHeadsHistory\"," +
            "    \"description\": \"The history of Melbourne CocoaHeads\"," +
            "    \"fork\": false," +
            "    \"url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory\"," +
            "    \"forks_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/forks\"," +
            "    \"keys_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/keys{/key_id}\"," +
            "    \"collaborators_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/collaborators{/collaborator}\"," +
            "    \"teams_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/teams\"," +
            "    \"hooks_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/hooks\"," +
            "    \"issue_events_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/issues/events{/number}\"," +
            "    \"events_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/events\"," +
            "    \"assignees_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/assignees{/user}\"," +
            "    \"branches_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/branches{/branch}\"," +
            "    \"tags_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/tags\"," +
            "    \"blobs_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/git/blobs{/sha}\"," +
            "    \"git_tags_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/git/tags{/sha}\"," +
            "    \"git_refs_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/git/refs{/sha}\"," +
            "    \"trees_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/git/trees{/sha}\"," +
            "    \"statuses_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/statuses/{sha}\"," +
            "    \"languages_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/languages\"," +
            "    \"stargazers_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/stargazers\"," +
            "    \"contributors_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/contributors\"," +
            "    \"subscribers_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/subscribers\"," +
            "    \"subscription_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/subscription\"," +
            "    \"commits_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/commits{/sha}\"," +
            "    \"git_commits_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/git/commits{/sha}\"," +
            "    \"comments_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/comments{/number}\"," +
            "    \"issue_comment_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/issues/comments{/number}\"," +
            "    \"contents_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/contents/{+path}\"," +
            "    \"compare_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/compare/{base}...{head}\"," +
            "    \"merges_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/merges\"," +
            "    \"archive_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/{archive_format}{/ref}\"," +
            "    \"downloads_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/downloads\"," +
            "    \"issues_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/issues{/number}\"," +
            "    \"pulls_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/pulls{/number}\"," +
            "    \"milestones_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/milestones{/number}\"," +
            "    \"notifications_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/notifications{?since,all,participating}\"," +
            "    \"labels_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/labels{/name}\"," +
            "    \"releases_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/releases{/id}\"," +
            "    \"deployments_url\": \"https://api.github.com/repos/melbournecocoa/MelbourneCocoaHeadsHistory/deployments\"," +
            "    \"created_at\": \"2013-05-11T02:31:05Z\"," +
            "    \"updated_at\": \"2022-05-11T20:15:40Z\"," +
            "    \"pushed_at\": \"2018-09-24T04:01:26Z\"," +
            "    \"git_url\": \"git://github.com/melbournecocoa/MelbourneCocoaHeadsHistory.git\"," +
            "    \"ssh_url\": \"git@github.com:melbournecocoa/MelbourneCocoaHeadsHistory.git\"," +
            "    \"clone_url\": \"https://github.com/melbournecocoa/MelbourneCocoaHeadsHistory.git\"," +
            "    \"svn_url\": \"https://github.com/melbournecocoa/MelbourneCocoaHeadsHistory\"," +
            "    \"homepage\": \"https://www.melbournecocoaheads.com\"," +
            "    \"size\": 57," +
            "    \"stargazers_count\": 8," +
            "    \"watchers_count\": 8," +
            "    \"language\": null," +
            "    \"has_issues\": true," +
            "    \"has_projects\": true," +
            "    \"has_downloads\": true," +
            "    \"has_wiki\": true," +
            "    \"has_pages\": false," +
            "    \"has_discussions\": false," +
            "    \"forks_count\": 3," +
            "    \"mirror_url\": null," +
            "    \"archived\": false," +
            "    \"disabled\": false," +
            "    \"open_issues_count\": 13," +
            "    \"license\": null," +
            "    \"allow_forking\": true," +
            "    \"is_template\": false," +
            "    \"web_commit_signoff_required\": false," +
            "    \"topics\": [" +
            "" +
            "    ]," +
            "    \"visibility\": \"public\"," +
            "    \"forks\": 3," +
            "    \"open_issues\": 13," +
            "    \"watchers\": 8," +
            "    \"default_branch\": \"master\"," +
            "    \"permissions\": {" +
            "      \"admin\": false," +
            "      \"maintain\": false," +
            "      \"push\": false," +
            "      \"triage\": false," +
            "      \"pull\": true" +
            "    }" +
            "  }," +
            "  {" +
            "    \"id\": 22910628," +
            "    \"node_id\": \"MDEwOlJlcG9zaXRvcnkyMjkxMDYyOA==\"," +
            "    \"name\": \"tmtw\"," +
            "    \"full_name\": \"melbournecocoa/tmtw\"," +
            "    \"private\": false," +
            "    \"owner\": {" +
            "      \"login\": \"melbournecocoa\"," +
            "      \"id\": 8436888," +
            "      \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjg0MzY4ODg=\"," +
            "      \"avatar_url\": \"https://avatars.githubusercontent.com/u/8436888?v=4\"," +
            "      \"gravatar_id\": \"\"," +
            "      \"url\": \"https://api.github.com/users/melbournecocoa\"," +
            "      \"html_url\": \"https://github.com/melbournecocoa\"," +
            "      \"followers_url\": \"https://api.github.com/users/melbournecocoa/followers\"," +
            "      \"following_url\": \"https://api.github.com/users/melbournecocoa/following{/other_user}\"," +
            "      \"gists_url\": \"https://api.github.com/users/melbournecocoa/gists{/gist_id}\"," +
            "      \"starred_url\": \"https://api.github.com/users/melbournecocoa/starred{/owner}{/repo}\"," +
            "      \"subscriptions_url\": \"https://api.github.com/users/melbournecocoa/subscriptions\"," +
            "      \"organizations_url\": \"https://api.github.com/users/melbournecocoa/orgs\"," +
            "      \"repos_url\": \"https://api.github.com/users/melbournecocoa/repos\"," +
            "      \"events_url\": \"https://api.github.com/users/melbournecocoa/events{/privacy}\"," +
            "      \"received_events_url\": \"https://api.github.com/users/melbournecocoa/received_events\"," +
            "      \"type\": \"Organization\"," +
            "      \"site_admin\": false" +
            "    }," +
            "    \"html_url\": \"https://github.com/melbournecocoa/tmtw\"," +
            "    \"description\": null," +
            "    \"fork\": false," +
            "    \"url\": \"https://api.github.com/repos/melbournecocoa/tmtw\"," +
            "    \"forks_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/forks\"," +
            "    \"keys_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/keys{/key_id}\"," +
            "    \"collaborators_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/collaborators{/collaborator}\"," +
            "    \"teams_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/teams\"," +
            "    \"hooks_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/hooks\"," +
            "    \"issue_events_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/issues/events{/number}\"," +
            "    \"events_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/events\"," +
            "    \"assignees_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/assignees{/user}\"," +
            "    \"branches_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/branches{/branch}\"," +
            "    \"tags_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/tags\"," +
            "    \"blobs_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/git/blobs{/sha}\"," +
            "    \"git_tags_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/git/tags{/sha}\"," +
            "    \"git_refs_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/git/refs{/sha}\"," +
            "    \"trees_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/git/trees{/sha}\"," +
            "    \"statuses_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/statuses/{sha}\"," +
            "    \"languages_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/languages\"," +
            "    \"stargazers_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/stargazers\"," +
            "    \"contributors_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/contributors\"," +
            "    \"subscribers_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/subscribers\"," +
            "    \"subscription_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/subscription\"," +
            "    \"commits_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/commits{/sha}\"," +
            "    \"git_commits_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/git/commits{/sha}\"," +
            "    \"comments_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/comments{/number}\"," +
            "    \"issue_comment_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/issues/comments{/number}\"," +
            "    \"contents_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/contents/{+path}\"," +
            "    \"compare_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/compare/{base}...{head}\"," +
            "    \"merges_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/merges\"," +
            "    \"archive_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/{archive_format}{/ref}\"," +
            "    \"downloads_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/downloads\"," +
            "    \"issues_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/issues{/number}\"," +
            "    \"pulls_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/pulls{/number}\"," +
            "    \"milestones_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/milestones{/number}\"," +
            "    \"notifications_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/notifications{?since,all,participating}\"," +
            "    \"labels_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/labels{/name}\"," +
            "    \"releases_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/releases{/id}\"," +
            "    \"deployments_url\": \"https://api.github.com/repos/melbournecocoa/tmtw/deployments\"," +
            "    \"created_at\": \"2014-08-13T09:40:37Z\"," +
            "    \"updated_at\": \"2016-12-04T03:31:05Z\"," +
            "    \"pushed_at\": \"2017-09-14T22:32:06Z\"," +
            "    \"git_url\": \"git://github.com/melbournecocoa/tmtw.git\"," +
            "    \"ssh_url\": \"git@github.com:melbournecocoa/tmtw.git\"," +
            "    \"clone_url\": \"https://github.com/melbournecocoa/tmtw.git\"," +
            "    \"svn_url\": \"https://github.com/melbournecocoa/tmtw\"," +
            "    \"homepage\": \"\"," +
            "    \"size\": 138458," +
            "    \"stargazers_count\": 2," +
            "    \"watchers_count\": 2," +
            "    \"language\": null," +
            "    \"has_issues\": true," +
            "    \"has_projects\": true," +
            "    \"has_downloads\": true," +
            "    \"has_wiki\": true," +
            "    \"has_pages\": false," +
            "    \"has_discussions\": false," +
            "    \"forks_count\": 2," +
            "    \"mirror_url\": null," +
            "    \"archived\": false," +
            "    \"disabled\": false," +
            "    \"open_issues_count\": 1," +
            "    \"license\": {" +
            "      \"key\": \"mit\"," +
            "      \"name\": \"MIT License\"," +
            "      \"spdx_id\": \"MIT\"," +
            "      \"url\": \"https://api.github.com/licenses/mit\"," +
            "      \"node_id\": \"MDc6TGljZW5zZTEz\"" +
            "    }," +
            "    \"allow_forking\": true," +
            "    \"is_template\": false," +
            "    \"web_commit_signoff_required\": false," +
            "    \"topics\": [" +
            "" +
            "    ]," +
            "    \"visibility\": \"public\"," +
            "    \"forks\": 2," +
            "    \"open_issues\": 1," +
            "    \"watchers\": 2," +
            "    \"default_branch\": \"master\"," +
            "    \"permissions\": {" +
            "      \"admin\": false," +
            "      \"maintain\": false," +
            "      \"push\": false," +
            "      \"triage\": false," +
            "      \"pull\": true" +
            "    }" +
            "  }]"
}